#!/usr/bin/php
<?php
// Arguments
$arguments = array(
    'd' => 'daemon',
    'f:' => 'file:',
    'c:' => 'config:'
);

$defaults = array(
    'c' => '/etc/cronphp',
    'config' => '/etc/cronphp',
);
$defaults = array(
    'config' => 'cronphp.config',
);

$options = array_merge($defaults, getopt(implode('', array_keys($arguments)), $arguments));

// Load configuration
if (is_file($options['config']) && is_readable($options['config'])) {
    $config = parse_ini_file($options['config']);

    // TODO: Make sure we have a valid configuration
} else {
    echo 'No configuration was found.' . PHP_EOL;
    exit(22);
}

// Only run in daemon mode if no file is passed
if ((isset($options['d']) || isset($options['daemon'])) && (!isset($options['f']) && !isset($options['file']))) {

    // Daemon

    // File locking
    /*$fp = fopen('/var/run/cronphp.pid', 'c');
    if (!flock($fp, LOCK_EX)) {
        echo 'You can only run one instance at the time' . PHP_EOL;
    }*/

    $keepRunning = false;
    $client = new CronPHP_Rest_Client();

    do {
        if ($keepRunning) {
            // Sleep for a while
            sleep(10);
        }

        // TODO: Figure out if we need to listen to signal for stoping the job
        $keepRunning = true;

        // Fetch the joblist from server
        $jobs = json_decode($client->get($config['endpoint'] . 'list/?server=' . $_ENV['HOSTNAME']));

        if (!is_array($jobs)) {
            trigger_error('Server did not return valid data when requesting list of cronjobs.', E_USER_WARNING);

            continue;
        }

        // Read the currently installed crontab
        $installedCrontab = new CronPHP_Crontab($config['crontab']);
        $installedCrontab->parse();

        // Create a clean crontab
        $newCrontab = new CronPHP_Crontab($config['crontab']);

        // Create the new crontab
        foreach ($jobs as $job) {
            $cronjob = new CronPHP_Crontab_Cronjob($job);
            $newCrontab->addJob($cronjob);
        }

        // Compare the crontabs to see if anything has changed.
        if ($installedCrontab != $newCrontab) {
            // Install the new crontab
            $newCrontab->write();
        }
    } while ($keepRunning);
} else if ((isset($options['d']) || isset($options['daemon'])) && (isset($options['f']) || isset($options['file']))) {
    echo 'You can\'t specify both daemon mode and file argument' . PHP_EOL;
    exit(1);
} else {

    // Cronjob run
    if (isset($options['f']) || isset($options['file'])) {
        $file = isset($options['f']) ? $options['f'] : $options['file'];
    } else {
        echo 'No specified job was found.' . PHP_EOL;
        exit(22);
    }

    // File locking
    /*$fp = fopen('/var/run/cronphp.' . crc32($file) . '.pid', 'c');
    if (!flock($fp, LOCK_EX)) {
        echo 'You can only run one instance at the time' . PHP_EOL;
    }*/

    // Start timer
    $start = time();
    $startMs = microtime(true);

    // Run cronjob
    exec($file, $output, $return);

    // Stop timer
    $end = time();
    $endMs = microtime(true);

    // Prepare a request to logging service
    $data = json_encode(
        array(
            'path'    => $file,
            'server' => $_ENV['HOSTNAME'],
            'start'  => '@' . $start,
            'end'    => '@' . $end,
            'runTime' => $endMs - $startMs,
            'response' => $return,
            'output' => implode($output, PHP_EOL),
        )
    );

    $client = new CronPHP_Rest_Client();
    $client->post($config['endpoint'] . 'log/', $data);
}

// Relase file lock
//fclose($fp);

class CronPHP_Rest_Client {

    private function getClient() {
        $client = curl_init();
        curl_setopt($client, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($client, CURLOPT_HEADER, false);

        return $client;
    }

    public function get($url) {
        $client = $this->getClient();

        curl_setopt($client, CURLOPT_URL, $url);
        curl_setopt($client, CURLOPT_POST, false);

        $response = curl_exec($client);
        curl_close($client);

        return $response;
    }

    public function post($url, $data) {
        $client = $this->getClient();

        curl_setopt($client, CURLOPT_URL, $url);
        curl_setopt($client, CURLOPT_POST, true);
        curl_setopt($client, CURLOPT_POSTFIELDS, 'data=' . $data);

        $response = curl_exec($client);
        curl_close($client);

        return $response;
    }
}

class CronPHP_Crontab {
    private $cronfile;
    private $crontab = array();

    public function __construct($cronfile = null) {
        if (!is_null($cronfile)) {
            $this->cronfile = $cronfile;
        }
    }

    public function parse($cronfile = null) {
        if (!is_null($cronfile)) {
            $this->cronfile = $cronfile;
        } else if (is_null($this->cronfile)) {
            throw new InvalidArgumentException('No cronfile was specified.');
        }

        if (!is_file($this->cronfile)) {
            $this->write();
        } else if (is_readable($this->cronfile)) {
            $crontab = file($this->cronfile);
            foreach ($crontab as $line) {
                $job = new CronPHP_Crontab_Cronjob(trim($line));
                $this->addJob($job);
            }
        } else {
            echo 'Unable to read crontab.' . PHP_EOL;
            exit(1);
        }
    }

    public function write($cronfile = null) {
        if (!is_null($cronfile)) {
            $this->cronfile = $cronfile;
        } else if (is_null($this->cronfile)) {
            throw new InvalidArgumentException('No cronfile was specified.');
        }

        if (!is_writable(dirname($this->cronfile))) {
            echo 'Unable to install crontab. Missing write access to "' . $this->cronfile . '"' . PHP_EOL;
            exit(1);
        }

        // TODO: Make sure we don't write any bogus cronjobs(wrong time, missing file, invalid user, etc)
        return file_put_contents($this->cronfile, $this->crontab);
    }

    public function addJob(CronPHP_Crontab_Cronjob $job) {
        $this->crontab[$job->path] = $job;

        return $this;
    }

    public function removeJob($path) {
        unset($this->crontab[$path]);

        return $this;
    }

    public function clear() {
        $this->crontab = array();

        return $this;
    }
}

class CronPHP_Crontab_Cronjob {
    public $path;
    public $user;
    public $minute = '0';
    public $hour = '*';
    public $dayOfMonth = '*';
    public $month = '*';
    public $dayOfWeek = '*';

    public function __construct($job) {

        if (is_string($job)) {
            $job = $this->parseJob($job);
        }

        $job = (array) $job;

        $this->path = $job['path'];
        $this->user = $job['user'];
        $this->minute = $job['minute'];
        $this->hour = $job['hour'];
        $this->dayOfMonth = $job['dayOfMonth'];
        $this->month = $job['month'];
        $this->dayOfWeek = $job['dayOfWeek'];
    }

    public function parseJob($line) {
        if (!preg_match('#^([0-9/* ]+) (\w+) (' . __FILE__ . ' -f) "(.+)"$#', $line, $matches)) {
            throw new InvalidArgumentException('Line does not match valid format.');
        }

        // Expand information from matches
        list($match, $time, $user, $cronphp, $path) = $matches;

        // Expand run times
        list($minute, $hour, $dayOfMonth, $month, $dayOfWeek) = explode(' ', $time);

        return array('path' => $path, 'user' => $user, 'minute' => $minute,  'hour' => $hour, 'dayOfMonth' => $dayOfMonth, 'month' => $month, 'dayOfWeek' => $dayOfWeek);
    }

    public function __toString() {
        return sprintf('%s %s %s %s %s %s %s -f "%s"', $this->minute, $this->hour, $this->dayOfMonth, $this->month, $this->dayOfWeek, $this->user, __FILE__ , $this->path) .  PHP_EOL;
    }
}
