<?php
$this->bodyClass = 'cronjob-list';
$this->pageName = 'Cronjobs';
$this->tagline = 'List of all configured cronjobs';
?>

<h2>Active cronjobs</h2>
<?php
echo $this->partial('cronjob/list-partial.phtml', array('listname' => 'active', 'cronjobs' => $this->activeCronjobs));
?>

<h2>Inactive cronjobs</h2>
<?php
echo $this->partial('cronjob/list-partial.phtml', array('listname' => 'inactive', 'cronjobs' => $this->inactiveCronjobs));
?>
