<table class="dataList" style="width: 100%">
<col class="string" />
<col class="string" />
<col class="string" />
<col class="string" />
<col class="string" />
<col class="string" />
<col class="string" />
<col class="string" />

  <thead>
    <tr>
        <th scope="col">Minute</th>
        <th scope="col">Hour</th>
        <th scope="col">Day of month</th>
        <th scope="col">Month</th>
        <th scope="col">Day of week</th>
        <th scope="col">User</th>
        <th scope="col">Path</th>
        <th scope="col">Server</th>
    </tr>
  </thead>
  <tbody>
<?php foreach ($this->cronjobs as $job) { ?>
    <tr>
        <td><?php echo $job->cronjobMinute ?></td>
        <td><?php echo $job->cronjobHour ?></td>
        <td><?php echo $job->cronjobDayOfMonth ?></td>
        <td><?php echo $job->cronjobMonth ?></td>
        <td><?php echo $job->cronjobDayOfWeek ?></td>
        <td><?php echo $job->cronjobUser ?></td>
        <td><?php echo $job->cronjobPath ?></td>
        <td><?php echo $job->cronjobServer ?></td>
    </tr>
<?php } ?>
  </tbody>
</table>
