<table class="<?php echo $this->listname ?>">
    <col class="string" />
    <col class="string" />
    <col class="string" />
    <col class="string" />
    <col class="string" />
    <col class="string" />
    <col class="string" />
    <col class="string" />
    <col class="string" />

  <thead>
    <tr>
        <th scope="col">Minute</th>
        <th scope="col">Hour</th>
        <th scope="col">Day of month</th>
        <th scope="col">Month</th>
        <th scope="col">Day of week</th>
        <th scope="col">User</th>
        <th scope="col">Path</th>
        <th scope="col">Server</th>
        <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($this->cronjobs as $job) { ?>
    <tr>
        <td><?php echo $job->cronjobMinute ?></td>
        <td><?php echo $job->cronjobHour ?></td>
        <td><?php echo $job->cronjobDayOfMonth ?></td>
        <td><?php echo $job->cronjobMonth ?></td>
        <td><?php echo $job->cronjobDayOfWeek ?></td>
        <td><?php echo $job->cronjobUser ?></td>
        <td><a href="<?php echo $this->url(array('cronjobId' => $job->cronjobId), 'cronjob-job-view') ?>"><?php echo $job->cronjobPath ?></a></td>
        <td><a href="<?php echo $this->url(array('server' => $job->cronjobServer), 'log-server'); ?>"><?php echo $job->cronjobServer ?></a></td>
        <td>
            <?php if ($job->isActive()) { ?>
                <a href="<?php echo $this->url(array('cronjobId' => $job->cronjobId, 'toggle' => 'disable'), 'cronjob-job-toggle') ?>" class="btn toggleJob danger">Disable</a>
            <?php } else { ?>
                <a href="<?php echo $this->url(array('cronjobId' => $job->cronjobId, 'toggle' => 'enable'), 'cronjob-job-toggle') ?>" class="btn toggleJob primary">Enable</a>
            <?php } ?>
        </td>
    </tr>
    <?php } ?>
  </tbody>
</table>
