<div class="topbar">
    <div class="fill">
        <div class="container">
            <a class="brand" href="<?php echo $this->baseUrl(); ?>">CronPHP</a>

            <ul class="nav">
                <li><a href="<?php echo $this->baseUrl('/cronjob/'); ?>">Cronjobs</a></li>
                <li><a href="<?php echo $this->baseUrl('/log/'); ?>">Logs</a></li>
            </ul>
        </div>
    </div>
</div>
