<?php echo $this->doctype(); ?>
<html>
<head>
    <?php echo $this->headTitle('CronPHP'); ?>

    <?php
    $this->headMeta()->setHttpEquiv('Content-Type', 'text/html; charset=utf-8');
    $this->headMeta()->appendName('viewport', 'initial-scale=1.0, user-scalable=no');
    echo $this->headMeta();
    ?>

    <?php
    $this->headLink()->prependStylesheet($this->baseUrl('css/bootstrap/bootstrap.min.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('css/cronphp.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('css/prettify/prettify.css'));
    echo $this->headLink();
    ?>

    <?php
    $this->headScript()->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js');
    $this->headScript()->appendFile($this->baseUrl('js/bootstrap/bootstrap-dropdown.js'));
    $this->headScript()->appendFile($this->baseUrl('js/bootstrap/bootstrap-twipsy.js'));
    $this->headScript()->appendFile($this->baseUrl('js/prettify/prettify.js'));
    $this->headScript()->appendFile($this->baseUrl('js/cronphp.js'));
    ?>
</head>

<body class="<?php echo $this->bodyClass ?>">
    <?php echo $this->partial('header.phtml'); ?>

    <div class="container">
        <div class="content">

            <div class="page-header">
                <h1><?php echo $this->pageName ?><?php if ($this->tagline) { ?> <small><?php echo $this->tagline ?></small><?php } ?></h1>
            </div>
            <div class="row">
                <?php $columns = $this->placeholder('rightbar')->count() > 0 ? 10 : 16; ?>
                <div class="span<?php echo $columns ?>">
                    <?php echo $this->layout()->content; ?>
                </div>
                <?php
                echo $this->placeholder('rightbar')
                    ->setPrefix('<div class="span6">')
                    ->setPostfix('</div>');
                ?>
            </div>
        </div>

        <footer>
            CronPHP
        </footer>
    </div>

    <?php
    echo $this->headScript();
    ?>
</body>
</html>
