<table class="dataList" style="width: 100%">
<col class="string" />
<col class="string" />
<col class="string" />
<col class="string" />
<col class="number" />
<col class="string" />

  <thead>
    <tr>
        <th scope="col">Cronjob</th>
        <th scope="col">Server</th>
        <th scope="col">Start time</th>
        <th scope="col">End time</th>
        <th scope="col">Execution time</th>
        <th scope="col">Exit code</th>
    </tr>
  </thead>
  <tbody>
<?php foreach ($this->list as $log) { ?>
    <tr>
        <td><?php echo $log->getCronjob() ?></td>
        <td><?php echo $log->getServer() ?></td>
        <td><?php echo $log->getStart() ?></td>
        <td><?php echo $log->getEnd() ?></td>
        <td><?php echo $log->getRunTime() ?></td>
        <td><?php echo $log->getResponse() ?></td>
    </tr>
<?php } ?>
  </tbody>
</table>
